name: Deploy on vercel
on:
  push:
    branches:
      - main
      - staging

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: deploy
        with:
          route: GET https://api.countapi.xyz/hit/wow/nice
          owner: octokit
          repo: request-action
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
