name: Deploy on vercel
on:
  push:
    branches:
      - main
      - staging

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: deploy
        with:
          route: GET https://api.countapi.xyz/hit/wow/niceeee
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.deploy }}"
