name: Deploy on vercel
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: GET https://api.countapi.xyz/hit/wow/niceeeerw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
